version: 2
jobs:
  docs:
    docker:
      - image: p3lim/lua-doc-parser:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - " SHA256:Z7XGiML5YDwnp+5vFrCMieiFvWNXtlSklAfPeIlzl60"
      - checkout
      - run: build
  release:
    docker:
      - image: p3lim/wow-packager:latest
    steps:
      - checkout
      - run: release.sh
workflows:
  version: 2
  docs_and_release:
    jobs:
      - docs:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /.*/
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          context: api-keys
